package au.com.shiftyjelly.pocketcasts.repositories.fingerprint

import kotlin.math.PI
import kotlin.math.sin
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Parity tests for [CloudFingerprinter] and [CloudReferenceMatcher] against
 * the server's Go `SpectralGenerator`. The expected hashes come from
 * [CloudFingerprintParityData], generated by the Go test
 * `internal/fingerprint/client_fixtures_test.go` — do not hand-edit.
 */
class CloudFingerprinterTest {

    // Mirrors the Go deterministicSignal (client_fixtures_test.go): runtime
    // variables + identical expression order so every double is bit-equal.
    private fun deterministicSignal(sampleRate: Int, seconds: Double): FloatArray {
        val freqs = doubleArrayOf(440.0, 1000.0, 2500.0, 880.0)
        val amps = doubleArrayOf(0.5, 0.3, 0.2, 0.1)
        val phases = doubleArrayOf(0.0, 0.5, 1.2, 0.0)
        val n = (sampleRate * seconds).toInt()
        return FloatArray(n) { i ->
            val t = i.toDouble() / sampleRate
            var v = 0.0
            for (k in freqs.indices) {
                v += amps[k] * sin(2.0 * PI * freqs[k] * t + phases[k])
            }
            v.toFloat()
        }
    }

    private fun stereo(sampleRate: Int, seconds: Double): FloatArray {
        val mono = deterministicSignal(sampleRate, seconds)
        return FloatArray(mono.size * 2) { i -> mono[i / 2] }
    }

    private fun fingerprinterWindows(samples: FloatArray, channels: Int, sampleRate: Int): List<CloudFingerprinter.Window> {
        val fp = CloudFingerprinter()
        // Push in 8192-sample chunks to exercise the streaming path.
        var offset = 0
        while (offset < samples.size) {
            val end = minOf(offset + 8192, samples.size)
            fp.pushSamples(samples.copyOfRange(offset, end), channels, sampleRate)
            offset = end
        }
        return fp.finish()
    }

    @Test
    fun `16 kHz mono windows match the server reference hashes`() {
        val windows = fingerprinterWindows(deterministicSignal(16000, 10.0), 1, 16000)
        assertEquals(3, windows.size)
        for (i in CloudFingerprintParityData.signal16kMonoWindows.indices) {
            assertEquals("window $i start_sec", i, windows[i].timestampSec)
            assertArrayEquals(
                "window $i hashes must match server SpectralGenerator",
                CloudFingerprintParityData.signal16kMonoWindows[i],
                windows[i].hashes,
            )
        }
    }

    @Test
    fun `44_1 kHz stereo windows match the server reference hashes after downmix and resample`() {
        val windows = fingerprinterWindows(stereo(44100, 10.0), 2, 44100)
        assertEquals(3, windows.size)
        for (i in CloudFingerprintParityData.signal44kStereoWindows.indices) {
            assertArrayEquals(
                "resampled window $i hashes must match server",
                CloudFingerprintParityData.signal44kStereoWindows[i],
                windows[i].hashes,
            )
        }
    }

    @Test
    fun `chunked pushes equal a single push`() {
        val samples = deterministicSignal(16000, 10.0)

        val chunked = fingerprinterWindows(samples, 1, 16000)

        val single = CloudFingerprinter()
        single.pushSamples(samples, 1, 16000)
        val whole = single.finish()

        assertEquals(chunked, whole)
    }

    @Test
    fun `windows are emitted only once their lookahead is available`() {
        val fp = CloudFingerprinter()
        // Push only the first 8 s of the 10 s signal: window 0 cannot complete
        // until frames past its target zone exist (~9.5 s of audio).
        val samples = deterministicSignal(16000, 10.0)
        fp.pushSamples(samples.copyOfRange(0, 16000 * 8), 1, 16000)
        assertTrue("no window should be emitted after only 8 s", fp.windowsSoFar().isEmpty())
    }
}
